[project]
name = "dskit"
version = "1.9.0"
description = "Template profesional para Data Science y AI Engineering"
authors = [
  { name = "cacelass" }
]
readme = "README.md"
requires-python = ">= 3.10"
license = { text = "Apache-2.0" }
dependencies = [
    "copier>=6.0",
    "joblib>=1.5.3",
    "numpy>=2.2.6",
    "pandas>=2.3.3",
    "pyyaml",
    "scikit-learn>=1.7.2",
]

[project.optional-dependencies]
dev = [
    "bandit",
    "black",
    "isort",
    "jinja2",
    "mypy",
    "pip-audit",
    "pre-commit",
    "pytest",
    "radon",
    "ruff",
    "types-PyYAML",
]

[build-system]
requires = ["setuptools>=65.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.ruff]
line-length = 100
target-version = "py312"
exclude = [
    "template/",
    ".venv",
    "dist",
]

[tool.ruff.lint]
select = ["E", "F", "W", "I"]
ignore = ["E501"]

[tool.isort]
profile = "black"
line_length = 100
skip = ["template", ".venv"]

[tool.mypy]
strict = true
ignore_missing_imports = true
exclude = ["template/", ".venv"]

[tool.bandit]
exclude_dirs = ["template", ".venv", "tests"]
skips = ["B101", "B404", "B603"]

[tool.radon]
max_cc = 10
exclude = ["template/", ".venv", "tests/"]
