[project]
name = "dskit"
version = "1.8.2"
description = "Template profesional para Data Science y AI Engineering"
authors = [
  { name = "cacelass" }
]
readme = "README.md"
requires-python = ">= 3.10"
license = { text = "GPL-3.0" }
dependencies = [
    "copier",
    "pyyaml",
]

[project.optional-dependencies]
dev = [
    "ruff",
    "pytest",
    "jinja2",
]

[build-system]
requires = ["setuptools>=65.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.ruff]
line-length = 100
target-version = "py312"
exclude = [
    "template/",
    ".venv",
    "dist",
]

[tool.ruff.lint]
select = ["E", "F", "W", "I"]
ignore = ["E501"]