from __future__ import annotations

from pathlib import Path

from agents.config import ProjectConfig, load_project_config
from agents.context import SharedContext


def test_load_project_config_missing_file_returns_defaults(tmp_path: Path):
    config = load_project_config(tmp_path)
    assert config == ProjectConfig()


def test_load_project_config_parses_flat_yaml(tmp_path: Path):
    (tmp_path / ".copier-answers.yml").write_text(
        "# Generated by copier\n"
        "_src_path: gh:owner/dskit\n"
        "project_name: Mi Proyecto\n"
        "project_slug: mi_proyecto\n"
        "ml_type: supervisado\n"
        "use_docker: true\n"
        "use_optuna: false\n"
    )
    config = load_project_config(tmp_path)
    assert config.project_name == "Mi Proyecto"
    assert config.project_slug == "mi_proyecto"
    assert config.use_docker is True
    assert config.use_optuna is False
    assert "_src_path" not in config.extra  # metadatos de copier, descartados a propósito


def test_shared_context_paths_are_relative_to_root(tmp_path: Path):
    ctx = SharedContext(root=tmp_path, config=ProjectConfig(project_slug="pkg"))
    assert ctx.data_dir == tmp_path / "data"
    assert ctx.raw_data_dir == tmp_path / "data" / "raw"
    assert ctx.package_dir == tmp_path / "pkg"
    assert ctx.models_dir == tmp_path / "models"


def test_runs_dir_only_for_redes_neuronales(tmp_path: Path):
    ctx_nn = SharedContext(root=tmp_path, config=ProjectConfig(ml_type="redes_neuronales"))
    ctx_other = SharedContext(root=tmp_path, config=ProjectConfig(ml_type="supervisado"))
    assert ctx_nn.runs_dir() == tmp_path / "runs"
    assert ctx_other.runs_dir() is None
